In [1]:
print('Hello!')

Hello!


Here are some examples of python relational operators in action.  Relational operators produce an output with type 'bool', or the numpy equivalent 'numpy.bool_'

In [2]:
import numpy as np
x=5
y=6

print(x==y) # line 1
print(x!=y) # line 2

val = x==y
print(type(val)) # line 3

val = np.equal(x,y) # this is equivalent to == but uses a function call 
print(type(val)) # line 4

val = x < y
print(val)  # line 5
val = x > y
print(val)  # line 6
val = x >= y
print(val)  # line 7
val = x <= y
print(val)  # line 8

False
True
<class 'bool'>
<class 'numpy.bool_'>
True
False
False
True


Some examples of working with logical operators.  Note that python is picky about how you write 'True' and 'False'.  It won't recognize 'true' or 'TRUE', just 'True'.

In [3]:
x = True
y = False
val = x and y
print(val)
val = x or y
print(val)
val = not y
print(val)

False
True
True


Here's an example of a vectorized logical operation.  Both x and y are lists of truth values.  The 'and' operator is applied to each corresponding pair of elements across the two lists.

In [4]:
x = [True, True, False]
y = [True, False, False]
val = x and y
print(val)

[True, False, False]


## Arrays

We will mostly be working with numpy arrays, not lists.  Lists are more flexible, in that there aren't as many constraints as what can be an element of a list.  But the mathematical operations that we will be using to simulate neural networks require the array type to be used.

In [8]:
import numpy as np

x1 = [8, 1, 4, 2, 3, 1] # this creates a 'list'
x2 = [8, 'hi']
print(type(x1), type(x2), type(x2[0]), type(x2[1]))
print('\n')

# these create arrays
x3 = np.array([8, 1, 4, 2, 3, 1])
x4 = np.zeros((1,10)) # a vector with one row, 10 columns
x5 = np.zeros((10,1)) # a vector with 10 rows, 1 column
print(type(x3),type(x3[0]))
print(x4,'\n')
print(x5)

print(type((1,1)))

<class 'list'> <class 'list'> <class 'int'> <class 'str'>


<class 'numpy.ndarray'> <class 'numpy.int64'>
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
<class 'tuple'>


In [9]:
import numpy as np

x1 = np.array(range(10))
x2 = np.array([6, 4, 2, 10, 8])
print(x1,x2,'\n')

# the shape notation with a vector
# basically this says the vector only has one dimension
# it is also possible to create an array with shape (10,1)
# which in certain scenarios behaves identically to (10,) but is 
# treated differently in other scenarios
print(x1.shape, x1.shape[0]) # (10,)
print(x2.shape, x2.shape[0]) # (5,)

# access the first element
print(x1[0])
print(x2[0])

[0 1 2 3 4 5 6 7 8 9] [ 6  4  2 10  8] 

(10,) 10
(5,) 5
0
6


In [10]:
# have to run the previous cell before running this and the next few
print(x1,x2,'\n')

print('SLICES:')
print(x1[:3])
print(x2[:4])
print(x2[2:])
print(x1[2:5])
print(x2[1:3])


[0 1 2 3 4 5 6 7 8 9] [ 6  4  2 10  8] 

SLICES:
[0 1 2]
[ 6  4  2 10]
[ 2 10  8]
[2 3 4]
[4 2]


In [11]:
print(x2,'\n')
print('INDEXING:')
print(x2[[2,1,0,4,3]])
print(x2[[2,2,2,0,0]])

inds = [2,1,0,4,3]
print(x2[inds])

[ 6  4  2 10  8] 

INDEXING:
[ 2  4  6  8 10]
[2 2 2 6 6]
[ 2  4  6  8 10]


In [12]:
x1 = np.array((range(10)))
x2 = np.array([58,59,60])
print(x1)
x1[:3] = x2
print(x1)

[0 1 2 3 4 5 6 7 8 9]
[58 59 60  3  4  5  6  7  8  9]


In [14]:
x1 = np.array((range(10)))
x2 = np.array([58,59,60])
print(x1)
x1[3:5] = x2
print(x1)

[0 1 2 3 4 5 6 7 8 9]


ValueError: could not broadcast input array from shape (3) into shape (2)

In [13]:
x1 = np.array((range(10)))
x2 = np.array([58,59,60])
print(x1)
x1[3:6] = x2
print(x1)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 58 59 60  6  7  8  9]


Here is a simple example of vectorized multiplication and division.  Unlike in Matlab, you don't use the .* and ./ notation.

In [15]:
x = np.array([1,2,3])
print(x*5,'\n')
print(x/2)

[ 5 10 15] 

[0.5 1.  1.5]


## Control flow

Here's the basic format of if statements

In [16]:
x=5
y=6
z=6

if x==y:
    print('they are equal!')
else:
    print('they are not equal!')

if x==y:
    print('x and y are equal')
elif x==z:
    print('well at least x and z are equal')
else:
    print('x is not equal to anything, sigh')
    
if True:
    print('I will always be printed')
else:
    print('I will never be executed')

they are not equal!
x is not equal to anything, sigh
I will always be printed


## For loops
The workhorse of programming.  Run the enclosed code for each element in a list.  The first term is the index variable you’ll use, then 'in', then you provide the list to iterate over.


In [17]:
count = 0
for i in range(5):
    count = count + i
print(count)
    
for i in range(5):
    count += i


10


## Nested for loops
### How many stars will print?

In [18]:
for i in range(4):
    for j in range(2,5):
        if j==3 or j==4:
            print('*', end='')


********

## While loops
A while loop will just keep looping as long as the condition is true

In [19]:
count = 0
flag = True
while flag:
   count = count + 1
   if count > 100:
      flag = False
print(flag, count)

# alternative way to do a while loop
count = 0
while True:
   count = count + 1
   if count > 100:
      break
print(count)

False 101
101


## Matrices

In [20]:
import numpy as np

x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x1.shape,x1.shape[0])
print(x1,'\n')

print(x1[2,2])
print(x1[1,:])
print(x1[:,1])
print(x1[0:2,0:2])

(3, 3) 3
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

9
[4 5 6]
[2 5 8]
[[1 2]
 [4 5]]


Logical operators work on vectors and matrices, and can be used to create masks

In [21]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x1 >= 5)


[[False False False]
 [False  True  True]
 [ True  True  True]]


In [22]:
print(x1[x1 >= 5])

[5 6 7 8 9]


## Random numbers
We use random numbers all the time in scientific computing / computational neuroscience.  Here are some examples of useful functions.  Many more are described at: https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html

In [23]:
import numpy as np
import numpy.random as r

# uniform distribution from [0 to 1)
print(r.rand(), r.rand())
# normal distribution with specified parameters vs standard unit normal
print(r.normal(5,3), r.randn())
# random integer from this range, exclusive of top 
print(r.randint(1,10))
# third argument is the shape of the array to be filled with random integers
print(r.randint(1,10,(3,3)))
# permute the order of a sequence/array
print(r.permutation(np.array(range(10))))

r.seed(1234)
print('\n',r.rand(), r.rand())

r.seed(1234)
print('\n',r.rand(), r.rand())


0.3230825420354766 0.268727522699004
2.297344402470488 -0.3953697838128485
5
[[2 3 1]
 [6 1 9]
 [8 2 3]]
[6 5 2 8 4 7 3 1 9 0]

 0.1915194503788923 0.6221087710398319

 0.1915194503788923 0.6221087710398319


## Open up WingIDE and show some plotting code!