## some of numpy operations

#### creating and reshaping numpy arrays

In [139]:
a = [[[ 1,  2,  3], [ 4,  5,  6]],
     [[ 7,  8,  9], [10, 11, 12]],
     [[13, 14, 15], [16, 17, 18]],
     [[19, 20, 21], [22, 23, 24]]]

print(a)

print(type(a))
# note that a is a Python list, not a numpy array

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]]
<class 'list'>


In [140]:
import numpy as np

# convert a list to a numpy array
b = np.array(a)

print(b)
print(b.shape)
print(type(b))
print()

# or directly like this from a list
c = np.array([[[ 11,  12,  13], [ 24,  25,  26]],
              [[ 17,  18,  19], [210, 211, 212]],
              [[113, 114, 115], [216, 217, 218]],
              [[119, 120, 121], [222, 223, 224]]])

print(c)
print(c.shape)
print(type(c))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
(4, 2, 3)
<class 'numpy.ndarray'>

[[[ 11  12  13]
  [ 24  25  26]]

 [[ 17  18  19]
  [210 211 212]]

 [[113 114 115]
  [216 217 218]]

 [[119 120 121]
  [222 223 224]]]
(4, 2, 3)
<class 'numpy.ndarray'>


In [141]:
# reshape numpy arrays

print(b)
print(b.shape)
print()

sz1 = b.shape[1]
sz2 = b.shape[2]

d = b.reshape(b.shape[0],b.shape[1]*b.shape[2])
print(d)
print(d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
(4, 2, 3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)


In [142]:
# reshape back to the original dimensions

print(d.shape)
e = d.reshape(d.shape[0], sz1, sz2)
print(e.shape)

(4, 6)
(4, 2, 3)


#### numpy math operations

In [143]:
a = np.array([6, 4, 1, 3, 2, 5, 4, 4, 3, 1, 4, 6])
b = np.array([2, 4, 1, 2, 1, 5, 2, 2, 3, 1, 4, 2])

In [144]:
# add constant to elements of a numpy array
print(a+1)

# add two numpy arrays of the same length
print(a+b)

# element-wise multiplication of two numpy arrays
print(a*b)

# element-wise division of two numpy arrays
print(a/b)

# dot product of two numpy arrays
print(np.dot(a, b))

[7 5 2 4 3 6 5 5 4 2 5 7]
[ 8  8  2  5  3 10  6  6  6  2  8  8]
[12 16  1  6  2 25  8  8  9  1 16 12]
[3.  1.  1.  1.5 2.  1.  2.  2.  1.  1.  1.  3. ]
116


#### finding values in a numpy array

In [146]:
print(a)

# get all the indices of a where a[i] = 4
idx = np.where(a==4)[0]
print(idx)

[6 4 1 3 2 5 4 4 3 1 4 6]
[ 1  6  7 10]


In [147]:
# let's unpack the pieces of this

x = (a==4)
print(x)
# you can see that this operation creates an array of Booleans

y = np.where(x)
print(y)
# where returns the indices with True values - a numpy equivalent of the find() commaand in Matlab

# but notice that y is actually a tuple of length 1, not actually an array of indices
print(type(y))
print(len(y))

# therefore, we address the first index of the tuple
z = y[0]
print(z)

# this is the same as what we started with
idx = np.where(a==4)[0]
print(idx)

[False  True False False False False  True  True False False  True False]
(array([ 1,  6,  7, 10]),)
<class 'tuple'>
1
[ 1  6  7 10]
[ 1  6  7 10]


#### Boolean operations on numpy arrays

In [148]:
print(a)
print(b)

[6 4 1 3 2 5 4 4 3 1 4 6]
[2 4 1 2 1 5 2 2 3 1 4 2]


In [149]:
# imagine we want to find indices that satisfy two sets of constraints

# for example, first, the indices of a whereby a[i] == 4
idx1 = np.where(a==4)[0]
print(idx1)

[ 1  6  7 10]


In [150]:
# and, second, the indices of a whereby a[i] == b[i]
idx2 = np.where(a==b)[0]
print(idx2)

[ 1  2  5  8  9 10]


In [151]:
# what if we want the indices where both of these are true
idx3 = np.where((a==4) and (a==b))[0]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [152]:
# while you can do this
print(True and False)

False


In [153]:
# and you can do this
print([True, False] and [True, True])

[True, True]


In [154]:
# you cannot do this
print(np.array([True, False]) and np.array([True, True]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [155]:
# the problem is that expressions like a==4 returns a numpy array
print(a==4)
print(type(a==4))

[False  True False False False False  True  True False False  True False]
<class 'numpy.ndarray'>


In [156]:
# you can do and with numpy arrays this way (technically, & is a bitwise operator)
print(np.array([True, False]) & np.array([True, True]))

[ True False]


In [157]:
# or this way
print(np.logical_and(np.array([True, False]), np.array([True, True])))

[ True False]


In [158]:
# you can also do logical or these ways
print(np.array([True, False]) | np.array([True, True]))
print(np.logical_or(np.array([True, False]), np.array([True, True])))

[ True  True]
[ True  True]


In [159]:
# so getting back to our original problem, you can do it these two ways
idx3 = np.where((a==4) & (a==b))[0]
print(idx3)
idx4 = np.where(np.logical_and((a==4), (a==b)))[0]
print(idx4)

[ 1 10]
[ 1 10]


#### other operations on numpy arrays

In [160]:
c = [0.453, 0.234, 0.235, 0.843, 0.523, 0.223, 0.513, 0.423, 0.284, 0.224]

# get the indices of the maximum values of a numpy array
idx = np.argmax(c)
print(c)
print(idx)
print(c[idx])
print()

# get the indices of the maximum values of a numpy array
idx = np.argmin(c)
print(c)
print(idx)
print(c[idx])

[0.453, 0.234, 0.235, 0.843, 0.523, 0.223, 0.513, 0.423, 0.284, 0.224]
3
0.843

[0.453, 0.234, 0.235, 0.843, 0.523, 0.223, 0.513, 0.423, 0.284, 0.224]
5
0.223
